### ISSUE TITLE
Master branch dies

### ISSUE THREAD

**Issue by kelson42** [openzim/phet#34]
Also the Docker image https://hub.docker.com/r/openzim/phet/

```
Copying compressed images beginning with: ZW
Copying compressed images beginning with: ZX
Copying compressed images beginning with: ZY
Copying compressed images beginning with: ZZ
Copying compressed images beginning with: Zundefined
Copying compressed images beginning with: Zundefined
Copying compressed images beginning with: undefined0

> phetscraper@1.0.0 export /phet
> node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts

Error: Cannot find module '../state/get/catalog.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/phet/steps/export.ts:29:28)
    at Module._compile (module.js:570:32)
    at Module.m._compile (/phet/node_modules/ts-node/src/index.ts:395:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/phet/node_modules/ts-node/src/index.ts:398:12)
    at Module.load (module.js:487:32)

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "export"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! phetscraper@1.0.0 export: `node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phetscraper@1.0.0 export script 'node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phetscraper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phetscraper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phetscraper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /phet/npm-debug.log

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! phetscraper@1.0.0 start: `npm run setup && npm run get && npm run transform && npm run export`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phetscraper@1.0.0 start script 'npm run setup && npm run get && npm run transform && npm run export'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phetscraper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run setup && npm run get && npm run transform && npm run export
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phetscraper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phetscraper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /phet/npm-debug.log
root@4c2d26b4d691:/phet# 

```

**Comment by kelson42** [comment]
This seems to have been fixed.
