### ISSUE TITLE
Broken with nodejs v10

### ISSUE THREAD

**Issue by kelson42** [openzim/phet#42]
```
$ npm start

> phetscraper@1.0.0 start /srv/phet
> npm run setup && npm run get && npm run transform && npm run export


> phetscraper@1.0.0 setup /srv/phet
> node steps/setup.js

fs.js:165
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:165:11)
    at Object.fs.mkdir (fs.js:854:14)
    at /srv/phet/steps/setup.js:10:16
    at FSReqWrap.oncomplete (fs.js:169:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phetscraper@1.0.0 setup: `node steps/setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phetscraper@1.0.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phetscraper@1.0.0 start: `npm run setup && npm run get && npm run transform && npm run export`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phetscraper@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
$ node --version
v10.3.0
$ npm --version
4.6.1
```

**Comment by kelson42** [comment]
@ISNIT0 You fix works fine, but now I have an other error, later.
```
Copying compressed images beginning with: ZW
Copying compressed images beginning with: ZX
Copying compressed images beginning with: ZY
Copying compressed images beginning with: ZZ
Copying compressed images beginning with: Zundefined
Copying compressed images beginning with: Zundefined
Copying compressed images beginning with: undefined0

> phetscraper@1.0.0 export /srv/phet
> node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts


/srv/phet/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
steps/export.ts (7,26): Cannot find module 'iso-639-3'. (2307)
    at getOutput (/srv/phet/node_modules/ts-node/src/index.ts:307:15)
    at /srv/phet/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/srv/phet/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/srv/phet/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/srv/phet/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phetscraper@1.0.0 export: `node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phetscraper@1.0.0 export script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phetsCopying compressed images beginning with: ZW
Copying compressed images beginning with: ZX
Copying compressed images beginning with: ZY
Copying compressed images beginning with: ZZ
Copying compressed images beginning with: Zundefined
Copying compressed images beginning with: Zundefined
Copying compressed images beginning with: undefined0

> phetscraper@1.0.0 export /srv/phet
> node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts


/srv/phet/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
steps/export.ts (7,26): Cannot find module 'iso-639-3'. (2307)
    at getOutput (/srv/phet/node_modules/ts-node/src/index.ts:307:15)
    at /srv/phet/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/srv/phet/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/srv/phet/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/srv/phet/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phetscraper@1.0.0 export: `node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phetscraper@1.0.0 export script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phetscraper@1.0.0 start: `npm run setup && npm run get && npm run transform && npm run export`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phetscraper@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
craper@1.0.0 start: `npm run setup && npm run get && npm run transform && npm run export`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phetscraper@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kelson42** [comment]
@ISNIT0 Any news on this would be really welcome. We have now 100.000+ downloads and 30.000+ active installation. We would like to release a new update of this app.

**Comment by ISNIT0** [comment]
@kelson42 Could you try the latest code please? 👍

**Comment by kelson42** [comment]
@ISNIT0 Thx, seems to work fine. I have computed new files and have put them online.
