### ISSUE TITLE
scraper crashes on container

### ISSUE THREAD

**Issue by rgaudin** [openzim/phet#48]
Followed the README for the container:

```sh
docker run --volume /data/:/phet/dist:rw openzim/phet:latest /bin/bash -c "cd /phet && npm i && npm start"
```
and got the following output:

```
npm WARN phetscraper@1.0.0 No repository field.

> phetscraper@1.0.0 start /phet
> npm run setup && npm run get && npm run transform && npm run export


> phetscraper@1.0.0 setup /phet
> node steps/setup.js


> phetscraper@1.0.0 get /phet
> node_modules/ts-node/dist/bin.js steps/getCategory.ts

Starting build
Got list of 0 simulations to fetch... Here we go!
Got 0 pages
Saved Catalog
Getting  simulations
Got the stuff!

> phetscraper@1.0.0 transform /phet
> node steps/transform.js

Compressing images, this will take a while
Copying compressed images beginning with: 00
[ hundreds of those lines]
Copying compressed images beginning with: ZY
Copying compressed images beginning with: ZZ
Copying compressed images beginning with: Zundefined
Copying compressed images beginning with: Zundefined
Copying compressed images beginning with: undefined0

> phetscraper@1.0.0 export /phet
> node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts

res/js/index.ts(13,9): error TS2687: All declarations of 'languages' must have identical modifiers.

npm ERR! Linux 4.16.12
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "export"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! phetscraper@1.0.0 export: `node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the phetscraper@1.0.0 export script 'node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phetscraper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phetscraper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phetscraper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /phet/npm-debug.log

npm ERR! Linux 4.16.12
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! phetscraper@1.0.0 start: `npm run setup && npm run get && npm run transform && npm run export`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phetscraper@1.0.0 start script 'npm run setup && npm run get && npm run transform && npm run export'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phetscraper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run setup && npm run get && npm run transform && npm run export
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phetscraper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phetscraper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /phet/npm-debug.log
```

As suggested in the above logs, I tried to update node and npm before starting the process

``` sh
docker run --volume /data/:/phet/dist:rw openzim/phet:latest /bin/bash -c "cd /phet && npm cache clean -f && npm install -g n && n stable && npm install -g npm@latest && npm i && npm start"
```

Got the following output

```
npm WARN using --force I sure hope you know what you are doing.
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
/usr/local/lib
└── n@4.1.0


     install : node-v10.15.3
       mkdir : /usr/local/n/versions/node/10.15.3
       fetch : https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-x64.tar.gz
   installed : v10.15.3

/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.9.0
added 54 packages from 9 contributors, removed 15 packages and updated 47 packages in 29.877s
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN phetscraper@1.0.0 No repository field.

up to date in 19.97s

> phetscraper@1.0.0 start /phet
> npm run setup && npm run get && npm run transform && npm run export


> phetscraper@1.0.0 setup /phet
> node steps/setup.js

fs.js:136
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:136:11)
    at Object.mkdir (fs.js:721:14)
    at /phet/steps/setup.js:10:16
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phetscraper@1.0.0 setup: `node steps/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phetscraper@1.0.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-15T08_48_26_649Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phetscraper@1.0.0 start: `npm run setup && npm run get && npm run transform && npm run export`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phetscraper@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-15T08_48_26_722Z-debug.log
```

Is the container broken or am I using it wrong?

**Comment by ISNIT0** [comment]
This line is suspicious: `Got list of 0 simulations to fetch... Here we go! `

When I run without Docker I get `1675 simulations to fetch`

When I run in Docker I get the same thing you get

**Comment by kelson42** [comment]
Will try to fix that today

**Comment by kelson42** [comment]
@ISNIT0 I have updated to nodejs12 and last version of modules.  It is commited on git master. The stuff works for me locally but I alway s get the following error in the Docker container:
```
res/js/index.ts(13,9): error TS2687: All declarations of 'languages' must have identical modifiers.
```

Any idea?

Whole end of log
```
Copying compressed images beginning with: ZV
Copying compressed images beginning with: ZW
Copying compressed images beginning with: ZX
Copying compressed images beginning with: ZY
Copying compressed images beginning with: ZZ
Copying compressed images beginning with: Zundefined
Copying compressed images beginning with: Zundefined
Copying compressed images beginning with: undefined0

> phetscraper@1.0.0 export /phet
> node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts

res/js/index.ts(13,9): error TS2687: All declarations of 'languages' must have identical modifiers.

npm ERR! Linux 4.15.0-48-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "export"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! phetscraper@1.0.0 export: `node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the phetscraper@1.0.0 export script 'node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phetscraper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/typescript/bin/tsc && node_modules/browserify/bin/cmd.js res/js/index.js  -t babelify --presets [es2015] -o res/js/dist.js && node_modules/ts-node/dist/bin.js steps/export.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phetscraper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phetscraper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /phet/npm-debug.log

npm ERR! Linux 4.15.0-48-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! phetscraper@1.0.0 start: `npm run setup && npm run get && npm run transform && npm run export`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phetscraper@1.0.0 start script 'npm run setup && npm run get && npm run transform && npm run export'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phetscraper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run setup && npm run get && npm run transform && npm run export
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phetscraper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phetscraper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /phet/npm-debug.log
```

**Comment by ISNIT0** [comment]
Building a docker image with the latest code and running seems to be working fine.
@kelson42 Can we try re-publishing a docker image?

**Comment by rgaudin** [comment]
👍 starts properly for me as well. @kelson42 ?

**Comment by kelson42** [comment]
great, new image built on Docker hub
