### ISSUE TITLE
New unhandled promise warning

### ISSUE THREAD

**Issue by kelson42** [openzim/phet#80]
```
$ npm start

> phetscraper@1.0.0 start /home/kelson/code/phet
> npm run setup && npm run get && npm run transform && npm run export


> phetscraper@1.0.0 setup /home/kelson/code/phet
> node steps/setup.js


> phetscraper@1.0.0 get /home/kelson/code/phet
> node_modules/ts-node/dist/bin.js steps/getCategory.ts

Getting categories...
- chemistry: 53
- earth-science: 25
- math: 42
- biology: 19
- physics: 106
 - physics/quantum-phenomena: 21
 - math/mathapplications: 11
 - physics/motion: 32
 - chemistry/general: 42
 - chemistry/quantum: 14
 - physics/sound-and-waves: 9
 - physics/heat-and-thermodynamics: 15
 - physics/work-energy-and-power: 14
 - math/mathconcepts: 31
 - physics/light-and-radiation: 24
 - physics/electricity-magnets-and-circuits: 25
Starting build with [1] languages
Got list of 83 simulations to fetch... Here we go!
+ [fr] vector-addition
+ [fr] curve-fitting
+ [fr] concentration
+ [fr] arithmetic
+ [fr] vector-addition-equations
+ [fr] proportion-playground
+ [fr] charges-and-fields
+ [fr] balloons-and-static-electricity
+ [fr] area-builder
+ [fr] balancing-act
+ [fr] function-builder-basics
+ [fr] build-a-fraction
+ [fr] diffusion
+ [fr] function-builder
+ [fr] rutherford-scattering
+ [fr] build-an-atom
+ [fr] ph-scale-basics
+ [fr] expression-exchange
+ [fr] bending-light
+ [fr] energy-forms-and-changes
+ [fr] balancing-chemical-equations
+ [fr] states-of-matter
+ [fr] number-line-integers
+ [fr] equality-explorer-two-variables
+ [fr] equality-explorer
+ [fr] equality-explorer-basics
+ [fr] gene-expression-essentials
+ [fr] energy-skate-park-basics
+ [fr] states-of-matter-basics
+ [fr] make-a-ten
+ [fr] molecule-shapes-basics
+ [fr] fractions-equality
+ [fr] fraction-matcher
+ [fr] fractions-intro
+ [fr] fractions-mixed-numbers
+ [fr] graphing-quadratics
+ [fr] forces-and-motion-basics
+ [fr] friction
+ [fr] gravity-and-orbits
+ [fr] wave-interference
+ [fr] waves-intro
+ [fr] area-model-introduction
+ [fr] gases-intro
+ [fr] isotopes-and-atomic-mass
+ [fr] circuit-construction-kit-dc-virtual-lab
+ [fr] gravity-force-lab-basics
+ [fr] capacitor-lab-basics
+ [fr] circuit-construction-kit-dc
+ [fr] pendulum-lab
+ [fr] gravity-force-lab
+ [fr] beers-law-lab
+ [fr] coulombs-law
+ [fr] hookes-law
+ [fr] masses-and-springs
+ [fr] ohms-law
+ [fr] masses-and-springs-basics
+ [fr] area-model-multiplication
+ [fr] faradays-law
+ [fr] area-model-algebra
+ [fr] area-model-decimals
+ [fr] molarity
+ [fr] projectile-motion
+ [fr] neuron
+ [fr] molecule-polarity
+ [fr] molecules-and-light
+ [fr] atomic-interactions
+ [fr] plinko-probability
+ [fr] wave-on-a-string
+ [fr] ph-scale
+ [fr] gas-properties
+ [fr] reactants-products-and-leftovers
+ [fr] least-squares-regression
+ [fr] graphing-slope-intercept
+ [fr] blackbody-spectrum
+ [fr] unit-rates
+ [fr] trig-tour
+ [fr] resistance-in-a-wire
+ [fr] under-pressure
+ [fr] graphing-lines
+ [fr] john-travoltage
+ [fr] molecule-shapes
+ [fr] color-vision
+ [fr] acid-base-solutions
Got 83 pages
Saved Catalog
Got https://phet.colorado.edu/sims/html/concentration/latest/concentration_fr.html
Got https://phet.colorado.edu/sims/html/charges-and-fields/latest/charges-and-fields_fr.html
Got https://phet.colorado.edu/sims/html/area-builder/latest/area-builder_fr.html
Got https://phet.colorado.edu/sims/html/arithmetic/latest/arithmetic_fr.html
Got https://phet.colorado.edu/sims/html/vector-addition-equations/latest/vector-addition-equations_fr.html
Got https://phet.colorado.edu/sims/html/proportion-playground/latest/proportion-playground_fr.html
Got https://phet.colorado.edu/sims/html/vector-addition/latest/vector-addition_fr.html
Got https://phet.colorado.edu/sims/html/balancing-act/latest/balancing-act_fr.html
Got https://phet.colorado.edu/sims/html/curve-fitting/latest/curve-fitting_fr.html
Got https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_fr.html
Got https://phet.colorado.edu/sims/html/function-builder-basics/latest/function-builder-basics_fr.html
Got https://phet.colorado.edu/sims/html/function-builder/latest/function-builder_fr.html
Got https://phet.colorado.edu/sims/html/build-a-fraction/latest/build-a-fraction_fr.html
Got https://phet.colorado.edu/sims/html/diffusion/latest/diffusion_fr.html
Got https://phet.colorado.edu/sims/html/ph-scale-basics/latest/ph-scale-basics_fr.html
Got https://phet.colorado.edu/sims/html/build-an-atom/latest/build-an-atom_fr.html
Got https://phet.colorado.edu/sims/html/rutherford-scattering/latest/rutherford-scattering_fr.html
Got https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_fr.html
Got https://phet.colorado.edu/sims/html/balancing-chemical-equations/latest/balancing-chemical-equations_fr.html
Got https://phet.colorado.edu/sims/html/equality-explorer-two-variables/latest/equality-explorer-two-variables_fr.html
Got https://phet.colorado.edu/sims/html/states-of-matter/latest/states-of-matter_fr.html
Got https://phet.colorado.edu/sims/html/equality-explorer-basics/latest/equality-explorer-basics_fr.html
Got https://phet.colorado.edu/sims/html/equality-explorer/latest/equality-explorer_fr.html
Got https://phet.colorado.edu/sims/html/energy-forms-and-changes/latest/energy-forms-and-changes_fr.html
Got https://phet.colorado.edu/sims/html/gene-expression-essentials/latest/gene-expression-essentials_fr.html
Got https://phet.colorado.edu/sims/html/energy-skate-park-basics/latest/energy-skate-park-basics_fr.html
Got https://phet.colorado.edu/sims/html/expression-exchange/latest/expression-exchange_fr.html
Got https://phet.colorado.edu/sims/html/states-of-matter-basics/latest/states-of-matter-basics_fr.html
Got https://phet.colorado.edu/sims/html/number-line-integers/latest/number-line-integers_fr.html
Got https://phet.colorado.edu/sims/html/fraction-matcher/latest/fraction-matcher_fr.html
Got https://phet.colorado.edu/sims/html/molecule-shapes-basics/latest/molecule-shapes-basics_fr.html
Got https://phet.colorado.edu/sims/html/fractions-equality/latest/fractions-equality_fr.html
Got https://phet.colorado.edu/sims/html/make-a-ten/latest/make-a-ten_fr.html
Got https://phet.colorado.edu/sims/html/graphing-quadratics/latest/graphing-quadratics_fr.html
Got https://phet.colorado.edu/sims/html/friction/latest/friction_fr.html
Got https://phet.colorado.edu/sims/html/fractions-intro/latest/fractions-intro_fr.html
Got https://phet.colorado.edu/sims/html/fractions-mixed-numbers/latest/fractions-mixed-numbers_fr.html
Got https://phet.colorado.edu/sims/html/gravity-and-orbits/latest/gravity-and-orbits_fr.html
Got https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_fr.html
Got https://phet.colorado.edu/sims/html/wave-interference/latest/wave-interference_fr.html
Got https://phet.colorado.edu/sims/html/gases-intro/latest/gases-intro_fr.html
Got https://phet.colorado.edu/sims/html/area-model-introduction/latest/area-model-introduction_fr.html
Got https://phet.colorado.edu/sims/html/waves-intro/latest/waves-intro_fr.html
Got https://phet.colorado.edu/sims/html/isotopes-and-atomic-mass/latest/isotopes-and-atomic-mass_fr.html
Got https://phet.colorado.edu/sims/html/capacitor-lab-basics/latest/capacitor-lab-basics_fr.html
Got https://phet.colorado.edu/sims/html/circuit-construction-kit-dc-virtual-lab/latest/circuit-construction-kit-dc-virtual-lab_fr.html
Got https://phet.colorado.edu/sims/html/hookes-law/latest/hookes-law_fr.html
Got https://phet.colorado.edu/sims/html/pendulum-lab/latest/pendulum-lab_fr.html
Got https://phet.colorado.edu/sims/html/beers-law-lab/latest/beers-law-lab_fr.html
Got https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_fr.html
Got https://phet.colorado.edu/sims/html/gravity-force-lab-basics/latest/gravity-force-lab-basics_fr.html
Got https://phet.colorado.edu/sims/html/masses-and-springs/latest/masses-and-springs_fr.html
Got https://phet.colorado.edu/sims/html/ohms-law/latest/ohms-law_fr.html
Got https://phet.colorado.edu/sims/html/coulombs-law/latest/coulombs-law_fr.html
Got https://phet.colorado.edu/sims/html/masses-and-springs-basics/latest/masses-and-springs-basics_fr.html
Got https://phet.colorado.edu/sims/html/faradays-law/latest/faradays-law_fr.html
Got https://phet.colorado.edu/sims/html/gravity-force-lab/latest/gravity-force-lab_fr.html
Got https://phet.colorado.edu/sims/html/neuron/latest/neuron_fr.html
Got https://phet.colorado.edu/sims/html/area-model-decimals/latest/area-model-decimals_fr.html
Got https://phet.colorado.edu/sims/html/area-model-multiplication/latest/area-model-multiplication_fr.html
Got https://phet.colorado.edu/sims/html/molarity/latest/molarity_fr.html
Got https://phet.colorado.edu/sims/html/projectile-motion/latest/projectile-motion_fr.html
Got https://phet.colorado.edu/sims/html/area-model-algebra/latest/area-model-algebra_fr.html
Got https://phet.colorado.edu/sims/html/molecule-polarity/latest/molecule-polarity_fr.html
Got https://phet.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light_fr.html
Got https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string_fr.html
Got https://phet.colorado.edu/sims/html/plinko-probability/latest/plinko-probability_fr.html
Got https://phet.colorado.edu/sims/html/atomic-interactions/latest/atomic-interactions_fr.html
Got https://phet.colorado.edu/sims/html/least-squares-regression/latest/least-squares-regression_fr.html
Got https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale_fr.html
Got https://phet.colorado.edu/sims/html/reactants-products-and-leftovers/latest/reactants-products-and-leftovers_fr.html
Got https://phet.colorado.edu/sims/html/gas-properties/latest/gas-properties_fr.html
Got https://phet.colorado.edu/sims/html/blackbody-spectrum/latest/blackbody-spectrum_fr.html
Got https://phet.colorado.edu/sims/html/graphing-slope-intercept/latest/graphing-slope-intercept_fr.html
Got https://phet.colorado.edu/sims/html/under-pressure/latest/under-pressure_fr.html
Got https://phet.colorado.edu/sims/html/acid-base-solutions/latest/acid-base-solutions-600.png
Got https://phet.colorado.edu/sims/html/resistance-in-a-wire/latest/resistance-in-a-wire_fr.html
Got https://phet.colorado.edu/sims/html/area-builder/latest/area-builder-600.png
Got https://phet.colorado.edu/sims/html/area-model-algebra/latest/area-model-algebra-600.png
Got https://phet.colorado.edu/sims/html/unit-rates/latest/unit-rates_fr.html
Got https://phet.colorado.edu/sims/html/area-model-decimals/latest/area-model-decimals-600.png
Got https://phet.colorado.edu/sims/html/area-model-introduction/latest/area-model-introduction-600.png
Got https://phet.colorado.edu/sims/html/arithmetic/latest/arithmetic-600.png
Got https://phet.colorado.edu/sims/html/area-model-multiplication/latest/area-model-multiplication-600.png
Got https://phet.colorado.edu/sims/html/atomic-interactions/latest/atomic-interactions-600.png
Got https://phet.colorado.edu/sims/html/balancing-act/latest/balancing-act-600.png
Got https://phet.colorado.edu/sims/html/balancing-chemical-equations/latest/balancing-chemical-equations-600.png
Got https://phet.colorado.edu/sims/html/beers-law-lab/latest/beers-law-lab-600.png
Got https://phet.colorado.edu/sims/html/bending-light/latest/bending-light-600.png
Got https://phet.colorado.edu/sims/html/graphing-lines/latest/graphing-lines_fr.html
Got https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity-600.png
Got https://phet.colorado.edu/sims/html/blackbody-spectrum/latest/blackbody-spectrum-600.png
Got https://phet.colorado.edu/sims/html/build-a-fraction/latest/build-a-fraction-600.png
Got https://phet.colorado.edu/sims/html/acid-base-solutions/latest/acid-base-solutions_fr.html
Got https://phet.colorado.edu/sims/html/trig-tour/latest/trig-tour_fr.html
Got https://phet.colorado.edu/sims/html/john-travoltage/latest/john-travoltage_fr.html
Got https://phet.colorado.edu/sims/html/build-an-atom/latest/build-an-atom-600.png
Got https://phet.colorado.edu/sims/html/capacitor-lab-basics/latest/capacitor-lab-basics-600.png
Got https://phet.colorado.edu/sims/html/color-vision/latest/color-vision_fr.html
Got https://phet.colorado.edu/sims/html/concentration/latest/concentration-600.png
Got https://phet.colorado.edu/sims/html/charges-and-fields/latest/charges-and-fields-600.png
Got https://phet.colorado.edu/sims/html/circuit-construction-kit-dc-virtual-lab/latest/circuit-construction-kit-dc-virtual-lab-600.png
Got https://phet.colorado.edu/sims/html/coulombs-law/latest/coulombs-law-600.png
Got https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc-600.png
Got https://phet.colorado.edu/sims/html/curve-fitting/latest/curve-fitting-600.png
Got https://phet.colorado.edu/sims/html/color-vision/latest/color-vision-600.png
Got https://phet.colorado.edu/sims/html/diffusion/latest/diffusion-600.png
Got https://phet.colorado.edu/sims/html/energy-forms-and-changes/latest/energy-forms-and-changes-600.png
Got https://phet.colorado.edu/sims/html/expression-exchange/latest/expression-exchange-600.png
Got https://phet.colorado.edu/sims/html/energy-skate-park-basics/latest/energy-skate-park-basics-600.png
Got https://phet.colorado.edu/sims/html/equality-explorer-basics/latest/equality-explorer-basics-600.png
Got https://phet.colorado.edu/sims/html/equality-explorer-two-variables/latest/equality-explorer-two-variables-600.png
Got https://phet.colorado.edu/sims/html/equality-explorer/latest/equality-explorer-600.png
Got https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes_fr.html
Got https://phet.colorado.edu/sims/html/faradays-law/latest/faradays-law-600.png
Got https://phet.colorado.edu/sims/html/fraction-matcher/latest/fraction-matcher-600.png
Got https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics-600.png
Got https://phet.colorado.edu/sims/html/fractions-equality/latest/fractions-equality-600.png
Got https://phet.colorado.edu/sims/html/function-builder/latest/function-builder-600.png
Got https://phet.colorado.edu/sims/html/fractions-intro/latest/fractions-intro-600.png
Got https://phet.colorado.edu/sims/html/fractions-mixed-numbers/latest/fractions-mixed-numbers-600.png
Got https://phet.colorado.edu/sims/html/function-builder-basics/latest/function-builder-basics-600.png
Got https://phet.colorado.edu/sims/html/friction/latest/friction-600.png
Got https://phet.colorado.edu/sims/html/gases-intro/latest/gases-intro-600.png
Got https://phet.colorado.edu/sims/html/graphing-lines/latest/graphing-lines-600.png
Got https://phet.colorado.edu/sims/html/gene-expression-essentials/latest/gene-expression-essentials-600.png
Got https://phet.colorado.edu/sims/html/gas-properties/latest/gas-properties-600.png
Got https://phet.colorado.edu/sims/html/graphing-quadratics/latest/graphing-quadratics-600.png
Got https://phet.colorado.edu/sims/html/graphing-slope-intercept/latest/graphing-slope-intercept-600.png
Got https://phet.colorado.edu/sims/html/gravity-and-orbits/latest/gravity-and-orbits-600.png
Got https://phet.colorado.edu/sims/html/gravity-force-lab-basics/latest/gravity-force-lab-basics-600.png
Got https://phet.colorado.edu/sims/html/hookes-law/latest/hookes-law-600.png
Got https://phet.colorado.edu/sims/html/gravity-force-lab/latest/gravity-force-lab-600.png
Got https://phet.colorado.edu/sims/html/least-squares-regression/latest/least-squares-regression-600.png
Got https://phet.colorado.edu/sims/html/isotopes-and-atomic-mass/latest/isotopes-and-atomic-mass-600.png
Got https://phet.colorado.edu/sims/html/masses-and-springs-basics/latest/masses-and-springs-basics-600.png
Got https://phet.colorado.edu/sims/html/make-a-ten/latest/make-a-ten-600.png
Got https://phet.colorado.edu/sims/html/masses-and-springs/latest/masses-and-springs-600.png
Got https://phet.colorado.edu/sims/html/molarity/latest/molarity-600.png
Got https://phet.colorado.edu/sims/html/molecule-polarity/latest/molecule-polarity-600.png
Got https://phet.colorado.edu/sims/html/molecule-shapes-basics/latest/molecule-shapes-basics-600.png
Got https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes-600.png
Got https://phet.colorado.edu/sims/html/john-travoltage/latest/john-travoltage-600.png
Got https://phet.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light-600.png
Got https://phet.colorado.edu/sims/html/number-line-integers/latest/number-line-integers-600.png
Got https://phet.colorado.edu/sims/html/ohms-law/latest/ohms-law-600.png
Got https://phet.colorado.edu/sims/html/ph-scale-basics/latest/ph-scale-basics-600.png
Got https://phet.colorado.edu/sims/html/pendulum-lab/latest/pendulum-lab-600.png
Got https://phet.colorado.edu/sims/html/neuron/latest/neuron-600.png
Got https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale-600.png
Got https://phet.colorado.edu/sims/html/proportion-playground/latest/proportion-playground-600.png
Got https://phet.colorado.edu/sims/html/plinko-probability/latest/plinko-probability-600.png
Got https://phet.colorado.edu/sims/html/projectile-motion/latest/projectile-motion-600.png
Got https://phet.colorado.edu/sims/html/reactants-products-and-leftovers/latest/reactants-products-and-leftovers-600.png
Got https://phet.colorado.edu/sims/html/resistance-in-a-wire/latest/resistance-in-a-wire-600.png
Got https://phet.colorado.edu/sims/html/rutherford-scattering/latest/rutherford-scattering-600.png
Got https://phet.colorado.edu/sims/html/states-of-matter-basics/latest/states-of-matter-basics-600.png
Got https://phet.colorado.edu/sims/html/states-of-matter/latest/states-of-matter-600.png
Got https://phet.colorado.edu/sims/html/trig-tour/latest/trig-tour-600.png
Got https://phet.colorado.edu/sims/html/unit-rates/latest/unit-rates-600.png
Got https://phet.colorado.edu/sims/html/under-pressure/latest/under-pressure-600.png
Got https://phet.colorado.edu/sims/html/vector-addition/latest/vector-addition-600.png
Got https://phet.colorado.edu/sims/html/vector-addition-equations/latest/vector-addition-equations-600.png
Got https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string-600.png
Got https://phet.colorado.edu/sims/html/waves-intro/latest/waves-intro-600.png
Got https://phet.colorado.edu/sims/html/wave-interference/latest/wave-interference-600.png
Got the stuff!

> phetscraper@1.0.0 transform /home/kelson/code/phet
> node --no-warnings node_modules/ts-node/dist/bin.js steps/transform.ts

Converting images...
 ████████████████████████████████████████ 100% | ETA: 0s | 83/83
Processing documents...
 ████████████████████████████████████████ 100% | ETA: 0s | 83/83
Done.

> phetscraper@1.0.0 export /home/kelson/code/phet
> npm run export-prebuild && node_modules/ts-node/dist/bin.js steps/export.ts


> phetscraper@1.0.0 export-prebuild /home/kelson/code/phet
> npm run build && node_modules/browserify/bin/cmd.js res/js/index.js -t babelify --presets [es2015] -o res/js/dist.js


> phetscraper@1.0.0 build /home/kelson/code/phet
> tsc

Creating phet_fr_2020-03.zim ...
(node:9110) UnhandledPromiseRejectionWarning: Error: failed to create temporary directory ./dist/phet_fr_2020-03.tmp
    at ZimCreator._createZimCreator (/home/kelson/code/phet/node_modules/@openzim/libzim/dist/ZimCreator.js:72:51)
    at new ZimCreator (/home/kelson/code/phet/node_modules/@openzim/libzim/dist/ZimCreator.js:68:14)
    at /home/kelson/code/phet/steps/export.ts:124:23
    at step (/home/kelson/code/phet/steps/export.ts:33:23)
    at Object.next (/home/kelson/code/phet/steps/export.ts:14:53)
    at fulfilled (/home/kelson/code/phet/steps/export.ts:5:58)
(node:9110) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9110) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kelson42** [comment]
I think this happens if the directory `dist` is not available, but this is in the git repo, so my fault.
